# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: slack-service

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10

# The `functions` block defines what code to deploy
functions:
  slack:
    handler: handler.slack
    # The `events` block defines how to trigger the handler.slack code
    events:
      - http:
          path: slack
          method: get
          cors: true
